package interpreter;

public enum TokenType {
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_BRACKET, RIGHT_BRACKET,
    PLUS, MINUS, DOT, COMMA, SEMICOLON, SLASH, STAR,

    EXCLAMATION, EXCLAMATION_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    IDENTIFIER, STRING, NUMBER,

    AND, OR, ELSE, IF, FALSE, TRUE, WHILE, FOR,
    NULL, PRINT, RETURN, SUPER, THIS, VAR, FUNCTION, CLASS,

    END_OF_FILE
}
